GET http://localhost:8090/rest/color HTTP/1.1

###

GET http://localhost:8090/rest/color/3 HTTP/1.1

###

POST http://localhost:8090/rest/color HTTP/1.1
Content-Type: application/json

{
    "name": "orange",
    "rgb": "#FFA500",
    "example": "귤"
}

###

PUT http://localhost:8090/rest/color/1 HTTP/1.1
Content-Type: application/json

{
    "seq": "1",
    "name": "skyblue",
    "rgb": "#FFA500",
    "example": "구름"
}